name: Autobuild README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env:
          OPEN_WEATHER_MAP_KEY: ${{secrets.WEATHER_VISUALCROSSING_MAP_KEY}}
      - name: Commit and push new README.md
        run: |-
          git diff
          git config --global user.email "${{secrets.GLOBAL_USER_EMAIL}}"
          git config --global user.name "${{secrets.GLOBAL_USER_NAME}}"
          git commit -a -m "Hourly content update" || exit 0
          git push